### ISSUE TITLE
Make Access Token and Refresh token in JWT format?

### ISSUE THREAD

**Issue by ziad696** [ebrahimmfadae/openid-connect-app#10]
how to change the access token and refresh token to be in jwt format instead default one?

**Comment by ebrahimmfadae** [comment]
Check this link https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#getresourceserverinfo

Here's the sample code

```ts
getResourceServerInfo() {
    return {
        scope: 'api:read offline_access',
        accessTokenFormat: 'jwt',
    }
}
```
