### ISSUE TITLE
What is the username and password 

### ISSUE THREAD

**Issue by ziad696** [ebrahimmfadae/openid-connect-app#9]
First of all, thank you for your tutorial, which currently I try to understanding to how to use panva/oidc-provider trough running your code in my machine, however, i cant authenticated, since i dont know the username and the password, can you give me more explanation about this, what thing i should do to use your code?

**Comment by ebrahimmfadae** [comment]
The default user functionality has some issues; I will fix them. For now, visit http://localhost:3005/register and create a new user. Then go back to http://localhost:3005 and follow the authentication flow with your new user; you don't need to change any field in the forms except username and password.

**Comment by ziad696** [comment]
okay, thank you very much
